#!/usr/bin/bash
set -eou pipefail

# Usage function
usage() {
  echo "Usage: $0 [-p] [-t TOKEN] FILE URL"
  echo "Query a GraphQL API with a .gql file."
  echo
  echo "  -p Pretty print output"
  echo "  -t TOKEN  Bearer token for authentication"
  echo
  exit 1
}

# Variables
DEPS=(curl jq tr)
PRETTY=false
TOKEN=""

# Check dependencies
for cmd in "${DEPS[@]}"; do
  command -v "$cmd" &>/dev/null || { echo "Error: $cmd is required."; exit 1; }
done

# Check command line options
while getopts ":pt:" opt; do
  case $opt in
    p) PRETTY=true ;;
    t) TOKEN="$OPTARG" ;;
    :) echo "Error: -$OPTARG requires an argument." >&2; exit 1 ;;
    *) usage ;;
  esac
done
shift $((OPTIND - 1))

# Check arguments
if [ $# -lt 2 ]; then
  echo "Error: missing arguments." >&2; usage
elif [ $# -gt 2 ]; then
  echo "Error: too many arguments." >&2; usage
elif [ ! -e "$1" ]; then
  echo "Error: file '$1' does not exist." >&2; exit 1
elif [ ! -f "$1" ]; then
  echo "Error: '$1' is not a regular file." >&2; exit 1
elif [ ! -r "$1" ]; then
  echo "Error: file '$1' is not readable." >&2; exit 1
fi

# Wrap in query object with jq
QUERY=$(jq -c -n --rawfile q "$1" '{ query: $q }')

# Build optional auth header parameter
AUTH_HEADER=()
if [ -n "$TOKEN" ]; then
  AUTH_HEADER=(-H "Authorization: Bearer $TOKEN")
fi

# Build curl command
COMMAND=$(curl -s -X POST -H "Content-Type: application/json" "${AUTH_HEADER[@]}" -d "$QUERY" "$2")

if $PRETTY; then
  echo "$COMMAND" | jq .
else
  echo "$COMMAND"
fi

